### ISSUE TITLE
how to use this module to my project?

### ISSUE THREAD

**Issue by yaodehaung** [Aditya-shahh/KYChain#1]
i interested your project , but i don't know how to use this module can add my project .

**Comment by Aditya-shahh** [comment]
Thanks for showing your interest. 
Since this is a prototype so I haven't scaled it yet for public users.
Nevertheless, you can refer these tutorials for creating a blockchain app using ethereum and react :
https://www.udemy.com/ethereum-and-solidity-the-complete-developers-guide
